name: Sync LeetCode Solutions

on:
  schedule:
  - cron '0 0 * * * '

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install LeetCode CLI
      run: npm install -g leetcode-cli

    - name: Login to LeetCode
      run: echo "${{ secret.LEETCODE_CREDENTIALS }}" | leetcode use -l

    - name: Fetch latest submissions
      run: | 
        leetcode list > solved_list.txt
        for problem in $(cat solved_list.txt); do
          leetcode show $problem -g -l python > solutions/$problem.py
        done
        git add
        git commit -m "Auto-syn latest LeeCode solutions"
        git push origin main
      
